import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {

    in property <string> results: "";
    in-out property <bool> opencurtain;
    callback divide-income(string);

    background: #313e50;
    GridLayout {
        padding: 20px;
        spacing: 20px;
        Row {
            Text {
                text: "Income Calculator";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
                color: white;
            }
        }

        Row {
            income := LineEdit {
                horizontal-alignment: center;
                placeholder-text: "Enter your number (IDR)";
                font-size: 16px;
                height: 35px;
            }
        }

        Row {
            Button {
                text: "Calculate";
                primary: true;
                height: 35px;
                clicked => {
                    root.opencurtain = !root.opencurtain;
                    divide_income(income.text)
                };
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                    Rectangle {
                        background: #33333e;
                        x: 0;
                        width: root.opencurtain ? 0px : parent.width / 2;
                        height: parent.height;
                        animate width {
                            duration: 250ms; easing: ease-in;
                        }
                    }

                    // Right Curtain
                    Rectangle {
                        background: #33333e;
                        x: root.opencurtain ? parent.width : parent.width / 2;
                        width: root.opencurtain ? 0px : parent.width / 2;
                        height: parent.height;

                        animate width {
                            duration: 250ms; easing: ease-in;
                        }
                        animate x {
                            duration: 250ms; easing: ease-in;
                        }
                    }
                }
            }
        }
    }
}
